"""One-command automation: run strategy + attribution + walk-forward, and write a
single consolidated report. State Street: "running things automatically is a big plus."

    python run_all.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPORT = ROOT / "reports" / "results_latest.md"

STEPS = [
    ("Strategy + M2 evaluation", "run_strategy.py"),
    ("Factor & cost attribution", "run_attribution.py"),
    ("Walk-forward validation", "run_walkforward.py"),
]


def main() -> None:
    parts = ["# SSGA Meta-Labeling — Consolidated Results\n",
             "_Auto-generated by run_all.py. Note: if FRED was unreachable, macro is",
             "proxied and M2/attribution numbers are not final._\n"]
    for title, script in STEPS:
        print(f"\n>>> {title} ({script}) ...")
        res = subprocess.run([sys.executable, str(ROOT / script)], capture_output=True, text=True)
        out = res.stdout.strip() or res.stderr.strip()
        print(out)
        parts.append(f"\n## {title}\n\n```\n{out}\n```\n")
    REPORT.write_text("\n".join(parts))
    print(f"\nConsolidated report -> {REPORT}")


if __name__ == "__main__":
    main()
